### PR TITLE
Gray out entries where confidence intervals overlap, prefix perm numbers with a 'p'

### PR DESCRIPTION
**Pull request by vext01**
This diff:
- prefixes all permutation numbers with a 'p'
- grays out results when the permutation confidence interval is disjoint from the mono-PHP confidence interval.

I started verifying some cases by hand to check my code and found some unexpected outcomes. After a load of debugging, I've found this is due to the fact that it is possible for the intervals to be disjoint when using the raw float values and errors, but overlapping once rounded to 3 decimal places.

E.g.:

Let i_x be an interval of the form [lo, hi].

Suppose:
- i_1 = [0.219375950470564, 0.22052391786127998]
- i_2 = [0.216993358079344, 0.219126628991216]

These intervals are disjoint. As there is a gap between the upper bound of i_2 and the lower bound of i_1.

If we round those, we get:
- i_1' = [0.219, 0.221]
- i_2' = [0.217, 0.219]

Now the upper bound of i_2' = the lower bound of i_1', so these overlap.

I wonder what we should do. In some sense I would like the reader to be able to verify whether the intervals overlap using the paper alone. As it stands you can't do this as overlap is computing using raw unrounded floats.

Ideas:
- Compute overlap using rounded values.
- Don't consider intervals butted right up against each other as overlapping.

Thoughts, @ltratt, @cfbolz?

### CODE REVIEW

**Comment by ltratt** [comment]
Good spot -- I hadn't thought of that!

Let's use what the reader sees on screen, which is 3 DP -- it seems the only sensible outcome to me.

**Comment by vext01** [comment]
My latest commit rounds timings and errors to 3 and 4 decimal places (respectively) prior to computing overlap. I've checked a few by hand and I think this looks ok -- screenshot attached showing some manual checking.

OK?

overlap

**Comment by vext01** [comment]
Key:
- Gray: intervals overlap
- Normal: Intervals don't overlap
- Bold >25% difference in relative performance

**Comment by ltratt** [comment]
I think we need to make the grey background a bit lighter -- grey on grey won't print very well. Otherwise it looks good!

**Comment by vext01** [comment]
This is `black!5` instead of `black!10`. Looks better?
gray

**Comment by ltratt** [comment]
Looks good! Shall I merge, or do you want to squash?

**Comment by vext01** [comment]
splat. go ahead.

**Pull request merged**
