### PR TITLE
Fixed deltablue due to Eco changes.

### PR DESCRIPTION
**Pull request by ptersilie**

### CODE REVIEW

**Comment by ltratt** [comment]
Some language boxes still show as red exclamation marks in my version of Eco?

**Comment by ptersilie** [comment]
Should be only one and only until the Python fix is merged.

**Comment by ptersilie** [comment]
Ah, seems like it forgot a few boxes even though when I checked all boxes were green. I fixed, squashed and pushed. Have another look please.

**Comment by ltratt** [comment]
There's still a box in `projectionTest` that is unfixed. Once that's done, we can merge.

**Comment by ptersilie** [comment]
That's so strange. I checked twice that all boxes are valid. It seems that if you fix some, then close and reopen, new errors arise. I now manually went through the file, not relying on the parsing status, and fixed all remaining strings and reopened to file to check if it's still valid. Should be fixed now.

**Comment by ltratt** [comment]
Looks good to me!

**Pull request merged**
