### PR TITLE
Table tweaks

### PR DESCRIPTION
**Pull request by vext01**
This PR:
- Moves support for drawing ASCII tables out of the (more complicated) latex table script.
- Adds support for showing the new "reverse composed" benchmarks.
- Adds a new table (or rather grid) for deltablue permutations.
- Tidies up the code a lot.

Someone who understands the number crunching behind kalibera method needs to review this code carefully. Perhaps @cfbolz?

I want to rename `confidence.py` to `latex_table.py`, but I will do that last before merge, so the "changed files" tab on GH makes sense.

I'm attaching a rough PDF of the results from our 1x15 run on bencher5. All warmups were set (arbitrarily) to 6. I'm not yet worrying about the numbers at this point -- I'm thinking solely about formatting and correctness of the number crunching. Later I will properly look at numbers and optimise/dimension properly.

The first two tables have a new column _PyHyp_c'_ (primed) which shows the results for the the composed benchmarks in the opposite direction to _PyHyp_c_. Blanks cells correspond to benchmarks which, in the standard composed variant, use `compile_py_meth()`. These benchmarks can't be run in the opposite direction as we can't yet embed PHP methods into Python classes. In other words we have no `compile_php_meth()` yet.

The second table, is showing the results for _PyHyp_c'_ relative to _PyHyp_c_, which arguably isn't much help, as we probably want to see the _PyPy_ and _Hippy_ results relative to _PyHyp_c'_. This would require another table, which, based on a conversation with @ltratt about paper real-estate, we might not have space for. Thoughts and suggestions welcome.

The third (new) table (or rather grid) shows the absolute and relative times of the deltablue permutations. Each cell shows the results for one permutation. The relative readings are relative to PyHyp running a mono-php version of deltablue. This should give us insight into which Python functions/methods impose the most/lest overhead. The grid you see it about the 3rd attempt at putting as much information into as little space as possible. What do you think?

CC @ltratt, @cfbolz.
[main.pdf](https://github.com/softdevteam/pyhyp_experiments/files/33996/main.pdf)

### CODE REVIEW

**Comment by vext01** [comment]
I wonder if alternating row shades would be favourable over the checker-board style shading we currently have.

**Comment by vext01** [comment]
Here is a sample which uses row shading. I think this is nicer.
[main.pdf](https://github.com/softdevteam/pyhyp_experiments/files/34010/main.pdf)

**Comment by ltratt** [comment]
Row shading is definitely better; but I think it would be better to sort things by column than by row.  Also, let's get rid of the vertical lines in the table -- LaTeX makes a mess of such things and they render really badly :(

**Comment by vext01** [comment]
I added the vertical lines because I found it hard to differentiate cells without them.

I'm not sure about ordering by column either. Reading from left to right feels more natural than down, no?

I will upload a sample with these two changes at some point.

**Comment by vext01** [comment]
Ah, were you reading the PDF in chrome? Chrome screws up rendering of the lines in the table.

**Comment by ltratt** [comment]
No, LaTeX draws these as multiple individual lines, so many PDF viewers don't render them consistently. This really is because LaTeX took a dumb decision... but we're stuck with it, so let's kill the vertical lines.

With multi-column stuff that spans multiple rows (as in this case), one invariably reads by column not row.

**Comment by vext01** [comment]
Here's the PDF with Laurie's suggestions. I find this quite a bit harder to read.
[main.pdf](https://github.com/softdevteam/pyhyp_experiments/files/34121/main.pdf)

**Comment by ltratt** [comment]
It's better IMHO. I actually wonder if it's worth getting rid of the `1, 2, 3...` markers, since I doubt we'll ever point at the thing and say "iteration 37 is weird"?

**Comment by vext01** [comment]
I disagree that it looks better. I will go as far as to say this is like one of those optical illusions that makes your eyes cross. I'm going to try one more thing to make it easier to differentiate cells in the same row.

I think we will need the labels, no? Surely we will say things like, "permutation _x_ was 2x slower because it makes extensive use of _y_"?

**Comment by ltratt** [comment]
I think it looks better than before, though I think we can probably improve the labels. Perhaps the problem is that the labels are too big? Maybe we could use a small font and put a colon after each e.g. "37:"? Warning: I don't design UIs for a living.

**Comment by vext01** [comment]
OK, I'll try that as well. The main issue I'm having is that it makes my head spin if I try and focus on a single cell.

Watch this space.

**Comment by vext01** [comment]
How do you find this?
[main.pdf](https://github.com/softdevteam/pyhyp_experiments/files/34163/main.pdf)

**Comment by ltratt** [comment]
Works for me, more-or-less. There is however a problem with the shading: the shaded box for row _n_ starts only at the top of the text of row _n_, but extends to the top of the text at row _n+1_ (i.e. it's not vertically aligned properly). I kinda feel we need some padding at the top of the row too, but I don't know how to go about this properly. However, the current situation is probably good enough to be going on with.

**Comment by vext01** [comment]
Padding between rows is easy enough. I don't know how to fix the vertical alignment in the row. It's only off by a pixel or two anyways.

I'll try adding padding between rows...

**Comment by vext01** [comment]
Eh, this is actually not easy. Shall we squash and merge? I don't think it's worth the effort to make this pixel perfect.

**Comment by ltratt** [comment]
Yes, squashing and merging now is the right way to go IMHO. We can adjust pixels at a later date. Squash away!

**Comment by vext01** [comment]
were you ok with renaming the script? I will do that now if so.

**Comment by vext01** [comment]
Ready to merge.

**Pull request merged**
